# Generated by Django 2.2 on 2019-05-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchquery',
            name='user',
        ),
    ]
